### ISSUE TITLE
Contact form7 database plugin needed

### ISSUE THREAD

**Issue by pbindage129** [wpgenius/WP-Setup-Automate#1]
Recommended plugins:

1. Contact Form 7 Database Addon – CFDB7
https://wordpress.org/plugins/contact-form-cfdb7/
3.  Advanced Contact form 7 DB
https://wordpress.org/plugins/advanced-cf7-db/

**Comment by sohamjoshi8275** [comment]
best plugine for contact form database: https://wordpress.org/plugins/advanced-cf7-db/
