### ISSUE TITLE
Disable options

### ISSUE THREAD

**Issue by MakarandMane** [wpgenius/WP-Setup-Automate#22]
**Elementor**

- [x] 1. Landing Pages
- [x] 8. Flexbox Container - inactive 
- [x] 2. Google Fonts	
- [x] 3. Google Fonts Load	- swap
- [x] 4. Load Font Awesome 4 Support	
- [x] 5. Generator Tag	
- [x] 6. Enable Unfiltered File Uploads	
- [x] 7. CSS Print Method	- internal (external when live)

**Comment by sohamjoshi8275** [comment]
@MakarandMane 
wp option update elementor_google_font 0
wp option update elementor_css_print_method "internal"
wp option update elementor_meta_generator_tag 1
wp option update elementor_experiment-container "inactive"
wp option update elementor_unfiltered_files_upload 0
wp option update elementor_load_fa4_shim "no"
